name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Test with Perl ${{ matrix.perl }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.32'
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Cache local files
        uses: actions/cache@v2
        with:
          path: ./local
          key: ${{ runner.os }}-perl-${{ matrix.perl }}-${{ hashFiles('./cpanfile.snapshot') }}
      - name: Coveralls
        uses: mihyaeru21/actions-report-coveralls-perl@v1
        with:
          flag-name: perl-${{ matrix.perl }}
      - run: carton install
      - name: Run tests
        env:
          HARNESS_PERL_SWITCHES: '-MDevel::Cover=+ignore,^local/|^t/'
        run: carton exec -- prove -lrv t
